apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alchemist.fullname" . }}-config
  labels:
    {{- include "alchemist.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.config.content | nindent 4 }}
