[package]
name = "alchemist"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
subprocess = "0.2.9" 
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "macros", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
futures = { version = "0.3" }
toml = "0.8"
leptos = { version = "0.6", features = ["ssr"] }
leptos_axum = "0.6"
axum = { version = "0.7", features = ["macros"] }
tower = { version = "0.4" }
tower-http = { version = "0.5", features = ["fs"] }
console_error_panic_hook = "0.1"
console_log = "1.0"
log = "0.4"
rayon = "1.10"

