[package]
name = "alchemist"
version = "0.1.0"
edition = "2021"

[lib]
name = "alchemist"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "alchemist"
path = "src/main.rs"
required-features = ["ssr"]

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
subprocess = { version = "=0.2.9", optional = true }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "macros", "chrono"], optional = true }
chrono = { version = "0.4", features = ["serde"] }
num_cpus = "1.16"
inquire = { version = "0.7", optional = true }
futures = { version = "0.3" }
toml = "0.8"
leptos = { version = "=0.6.14" }
leptos_axum = { version = "=0.6.14", optional = true }
axum = { version = "0.7", features = ["macros"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
console_error_panic_hook = "0.1"
console_log = "1.0"
log = "0.4"
rayon = "1.10"
tokio-stream = { version = "0.1", features = ["sync"], optional = true }
gloo-net = { version = "0.5", optional = true }
leptos_meta = "=0.6.14"
leptos_router = "=0.6.14"
leptos_dom = "=0.6.14"

thiserror = "2.0.17"
wasm-bindgen = "0.2"
notify = { version = "6", optional = true }
reqwest = { version = "0.12", features = ["json"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[features]
default = ["ssr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate", "dep:gloo-net"]
ssr = [
    "dep:tokio",
    "dep:subprocess",
    "dep:sqlx",
    "dep:leptos_axum",
    "dep:axum",
    "dep:tower",
    "dep:tower-http",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:inquire",
    "dep:notify",
    "dep:reqwest",
    "dep:tokio-stream",
]

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
bin-package = "alchemist"
output-name = "alchemist"

# The package where the secondary binary (include-path) is located
# If the secondary binary is in the same package, this should be the same as the bin-package
lib-package = "alchemist"

# The site root folder is where cargo-leptos generate all output. 
# WARNING: all content of this folder will be erased on a rebuild. 
# Use it in your server setup.
site-root = "target/site"

# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to "pkg"
site-pkg-dir = "pkg"

# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into main.css
style-file = "style/main.css"

# [Optional] Assets source directory. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
assets-dir = "public"

# The IP and port (eg: 127.0.0.1:3000) where the server serves the content. 
# Use it in your server setup.
site-addr = "127.0.0.1:3000"

# The port to use for automatic reload monitoring
reload-port = 3001

# [Optional] Command to use when running end2end tests. 
# Defaults to "cargo test --test end2end"
end2end-test-cmd = "cargo test --test end2end"

# [Optional] The browser to use for end2end tests. 
# Choices are: chrome, firefox, safari, playwright
end2end-browser = "chrome"

#  The browserlist query used for optimizing the SSR output
browserquery = "defaults"

# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"

# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the total size of the compiled JS/WASM (including deps) exceeds this threshold, 
# then a warning is emitted. (default 2MB)
# wasm-publish-debug-info = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# [Optional] The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1

