[package]
name = "alchemist"
version = "0.2.2"
edition = "2021"
license = "GPL-3.0"

[lib]
name = "alchemist"

[[bin]]
name = "alchemist"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
subprocess = { version = "=0.2.9" }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "macros", "chrono", "migrate"] }
chrono = { version = "0.4", features = ["serde"] }
num_cpus = "1.16"
inquire = { version = "0.7" }
futures = { version = "0.3" }
toml = "0.8"
axum = { version = "0.7", features = ["macros"] }
tower = { version = "0.4" }
tower-http = { version = "0.5", features = ["fs"] }
log = "0.4"
rayon = "1.10"
tokio-stream = { version = "0.1", features = ["sync"] }
thiserror = "2.0.17"
notify = { version = "6" }
reqwest = { version = "0.12", features = ["json"] }
rust-embed = { version = "8", features = ["axum"] }
mime_guess = "2.0"
async-trait = "0.1"
argon2 = "0.5.3"
rand = "0.8"
