apiVersion: v2
name: alchemist
description: AV1 video transcoding automation server
type: application
version: 0.1.0
appVersion: "0.2.0"
keywords:
  - transcoding
  - av1
  - video
  - ffmpeg
  - media
home: https://github.com/BrooklynLovesZelda/alchemist
sources:
  - https://github.com/BrooklynLovesZelda/alchemist
maintainers:
  - name: BrooklynLovesZelda
